python code.py --dataset cora --feature embeddings --p 0.25 --q 0.25 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.25 --q 0.5 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.25 --q 1 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.25 --q 2 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.25 --q 4 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.5 --q 0.25 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.5 --q 0.5 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.5 --q 1 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.5 --q 2 >> result.txt
python code.py --dataset cora --feature embeddings --p 0.5 --q 4 >> result.txt
python code.py --dataset cora --feature embeddings --p 1 --q 0.25 >> result.txt
python code.py --dataset cora --feature embeddings --p 1 --q 0.5 >> result.txt
python code.py --dataset cora --feature embeddings --p 1 --q 1 >> result.txt
python code.py --dataset cora --feature embeddings --p 1 --q 2 >> result.txt
python code.py --dataset cora --feature embeddings --p 1 --q 4 >> result.txt
python code.py --dataset cora --feature embeddings --p 2 --q 0.25 >> result.txt
python code.py --dataset cora --feature embeddings --p 2 --q 0.5 >> result.txt
python code.py --dataset cora --feature embeddings --p 2 --q 1 >> result.txt
python code.py --dataset cora --feature embeddings --p 2 --q 2 >> result.txt
python code.py --dataset cora --feature embeddings --p 2 --q 4 >> result.txt
python code.py --dataset cora --feature embeddings --p 4 --q 0.25 >> result.txt
python code.py --dataset cora --feature embeddings --p 4 --q 0.5 >> result.txt
python code.py --dataset cora --feature embeddings --p 4 --q 1 >> result.txt
python code.py --dataset cora --feature embeddings --p 4 --q 2 >> result.txt
python code.py --dataset cora --feature embeddings --p 4 --q 4 >> result.txt

python code.py --dataset citeseer --feature embeddings --p 0.25 --q 0.25 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.25 --q 0.5 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.25 --q 1 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.25 --q 2 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.25 --q 4 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.5 --q 0.25 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.5 --q 0.5 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.5 --q 1 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.5 --q 2 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 0.5 --q 4 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 1 --q 0.25 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 1 --q 0.5 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 1 --q 1 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 1 --q 2 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 1 --q 4 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 2 --q 0.25 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 2 --q 0.5 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 2 --q 1 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 2 --q 2 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 2 --q 4 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 4 --q 0.25 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 4 --q 0.5 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 4 --q 1 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 4 --q 2 >> result.txt
python code.py --dataset citeseer --feature embeddings --p 4 --q 4 >> result.txt

python code.py --dataset amazon_photo --feature embeddings --p 0.25 --q 0.25 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.25 --q 0.5 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.25 --q 1 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.25 --q 2 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.25 --q 4 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.5 --q 0.25 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.5 --q 0.5 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.5 --q 1 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.5 --q 2 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 0.5 --q 4 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 1 --q 0.25 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 1 --q 0.5 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 1 --q 1 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 1 --q 2 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 1 --q 4 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 2 --q 0.25 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 2 --q 0.5 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 2 --q 1 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 2 --q 2 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 2 --q 4 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 4 --q 0.25 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 4 --q 0.5 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 4 --q 1 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 4 --q 2 >> result.txt
python code.py --dataset amazon_photo --feature embeddings --p 4 --q 4 >> result.txt