objective: regression

dataset: ESOL
data_dir: ./data
mode: train
device: cuda

num_outputs: 1
num_targets: 1

batch_size: 256
epochs: 200
lr: 0.003
weight_decay: 0.00001
metric_direction: min
early_stop_count: 200

hidden_channels: 200
num_layers: 2
num_timesteps: 2
dropout: 0.2

model_path: ./checkpoints/esol.pth
submission_path: ./answer/ESOL-pred.csv

